fix opcode
S2E/guest-tools pull request #32
Opened 2019-01-14 17:00 UTC by borzacchiello

Looking at [1] it seems that the input registers of S2EConcretize are wrong. In particular: 
- _ecx_ for the buffer (in place of _eax_) 
- _eax_ for the size (in place of _edx_)

[1] https://github.com/S2E/libs2eplugins/blob/master/src/s2e/Plugins/Core/BaseInstructions.cpp#L407

Signed-off-by: Luca Borzacchiello <lucaborza@gmail.com>

2019-01-14 17:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/S2E/guest-tools?pullRequest=32) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/S2E/guest-tools?pullRequest=32) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/S2E/guest-tools?pullRequest=32) it.</sub>

2019-01-14 17:20 UTC, vitalych commented on windows/libcommon/src/i386/s2e.asm
> +    mov eax, _Buffer
Can you check that the 64-bit version is correct and fix it if needed?

2019-01-14 17:21 UTC, vitalych commented
Please rename your commit to `windows: fixed register use in S2EConcretize` or something like that. It should be more informative to someone who browses the commit log.

2019-01-14 17:21 UTC, vitalych requested changes
Nice catch, few comments above.

2019-01-14 21:36 UTC, borzacchiello commented on windows/libcommon/src/i386/s2e.asm
> +    mov eax, _Buffer
The x64 version had the same issue. I just modified the commit with the fix.

2019-03-03 19:46 UTC, vitalych approved these changes

2019-03-03 20:16 UTC, vitalych commented
@borzacchiello I wanted to rebase and merge your PR, looks like I need permissions to edit it. The github "update" button messed it up by adding a merge commit and I can't figure out how to undo that myself.

2019-03-10 13:26 UTC, borzacchiello commented
@vitalych I checked the box "Allow edits from maintainers.". Let me know if I have to do something else.

2019-03-10 13:39 UTC, merged

2019-03-10 13:40 UTC, vitalych commented
@borzacchiello turns out my git client was too old and couldn't authenticate.