s2e.so: fixed process memory map address ranges
S2E/guest-tools pull request #8
Opened 2017-08-29 01:24 UTC by adrianherrera

The calculation of the "limit" address for an entry in the process memory map was incorrect. The previous method only looked at executable entries in the process memory map. However, it is common for non-executable entries in the same virtual address space to follow the executable entry.

The process memory map parsing logic was updated to handle these cases. The parsing code now uses inodes to determine new entries in the process memory map. While the inode remains unchanged, the "limit" address is checked to ensure that the maximum address is saved into the final process memory map.

This assumes that entries of the same inode share a contiguous virtual address space. I think that this is a reasonable assumption.

2017-09-20 23:53 UTC, adrianherrera commented
@vitalych do you have any thoughts on this? Does it make sense?

2017-10-04 09:30 UTC, vitalych commented
It should be a good enough approximation for now. I think in general, sections of a module can be loaded anywhere in memory, not necessarily contiguously. We'd have to change ModuleDescriptor to take this into account.

2017-10-04 09:31 UTC, vitalych commented on linux/s2e.so/s2e.c
> +    // Read /proc/self/maps until we can initialize previous_inode to a non-zero inoda and then initialize the first
inoda => inode?

2017-10-04 09:32 UTC, vitalych commented on linux/s2e.so/s2e.c
> +    // Read /proc/self/maps until we can initialize previous_inode to a non-zero inoda and then initialize the first
It would be good to add the format of /proc/self/maps as a comment in the code.
Basically, paste your commit msg into the code.

2017-10-04 09:32 UTC, vitalych requested changes
.

2017-10-04 12:08 UTC, adrianherrera commented
Done! Documentation added into the code

2017-10-04 15:50 UTC, vitalych approved these changes

2017-10-05 00:46 UTC, merged